from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd


def heaviside_closed(lb, x):
    """
    Calculate the value of Heaviside function \mathbf{1}_{[lb,\infty)}(x)

    Args:
        lb (float): the left endpoint of the interval of the Heaviside function
        x (float): the variable of the Heaviside function

    Returns:
        int: 0 or 1
    """
    if x >= lb:
        return 1
    else:
        return 0


def heaviside_open(lb, x):
    """
    Calculate the value of Heaviside function \mathbf{1}_{(lb,\infty)}(x)

    Args:
        lb (float): the left endpoint of the interval of the Heaviside function
        x (float): the variable of the Heaviside function

    Returns:
        int: 0 or 1
    """
    if x > lb:
        return 1
    else:
        return 0


def calculate_gamma(X_train, y_train, weights, bias, beta_p, epsilon):
    """
    Compute the violation amount \gamma and the initial solutions of binary variables z^+_0, z^+, z^- 
    Used in precision constrained problem

    Args:
        X_train (ndarray): training set: X
        y_train (ndarray): training set: y
        weights (ndarray): parameter w in classification score w^\top X+b
        bias (float): parameter b in classification score w^\top X+b
        beta_p (float): precision lower bound
        epsilon (float): epsilon

    Returns:
        tuple[int, dict, dict, dict]: gamma,  z_plus_0_start, z_plus_start, z_minus_start
                                      \gamma, z^+_0,          z^+,          z^-
    """
    positive_index = np.where(y_train == 1)[0].tolist()
    negative_index = np.where(y_train == -1)[0].tolist()
    sum_tp = sum(heaviside_closed(0, np.dot(weights, X_train[s]) + bias) for s in positive_index)  
    sum_dm = sum(heaviside_closed(0, np.dot(weights, X_train[s]) + bias) for s in positive_index) + sum(heaviside_open(-epsilon, np.dot(weights, X_train[s]) + bias) for s in negative_index)
    gamma = max(0, - (sum_tp - beta_p * sum_dm))
    z_plus_0_start, z_plus_start, z_minus_start = {}, {}, {}

    for s in positive_index:
        z_plus_0_start[s] = heaviside_closed(0, np.dot(weights, X_train[s]) + bias - 1)
        z_plus_start[s] = heaviside_closed(0, np.dot(weights, X_train[s]) + bias)
    for s in negative_index:
        z_plus_0_start[s] = heaviside_closed(0, -np.dot(weights, X_train[s]) - bias - 1)
        z_minus_start[s] = heaviside_closed(0, -(np.dot(weights, X_train[s]) + bias) - epsilon)
    return gamma, z_plus_0_start, z_plus_start, z_minus_start  # if gamma > 0, initial solution generated by LinearClassifier is not feasible


def calculate_z(X_train, y_train, weights, bias):
    """
    Compute the initial solution of binary variable z^+_0
    Used in unconstrained problem, in which there are only z^+_0, no z^+, z^- and precision constraint violation \gamma

    Args:
        X_train (ndarray): training set: X
        y_train (ndarray): training set: y
        weights (ndarray): parameter w in classification score w^\top X+b
        bias (float): parameter b in classification score w^\top X+b

    Returns:
        dict: z_plus_0_start (intial solution of z^+_0)
    """
    positive_index = np.where(y_train == 1)[0].tolist()
    negative_index = np.where(y_train == -1)[0].tolist()
    
    z_plus_0_start = {}
    
    for s in positive_index:
        z_plus_0_start[s] = heaviside_closed(0, np.dot(weights, X_train[s]) + bias - 1)
        
    for s in negative_index:
        z_plus_0_start[s] = heaviside_closed(0, -np.dot(weights, X_train[s]) - bias - 1)
        
    return z_plus_0_start


def calculate_delta(X_train, y_train, weight, bias, epsilon, base_rate):
    """
    The index sets {\cal J}_{0;<}, {\cal J}_{0;>}, {\cal J}_{0;0} and {\cal J}_{1;<}, {\cal J}_{1;>}, {\cal J}_{1;0} are determined by the value
    of \phi(w,b):

        {\cal J}_{0;<} = \{ s | \phi_{0s}(w, b) < -\delta_2{0} \}
        {\cal J}_{0;>} = \{ s | \phi_{0s}(w, b) > \delta_1{0} \}
        {\cal J}_{0;0} = \{ s | -\delta_2{0} \le \phi_{0s}(w, b) \le \delta_1{0} \}

        {\cal J}_{1;<} = \{ s | \phi_{1s}(w, b) < -\delta_2{1} \}
        {\cal J}_{1;>} = \{ s | \phi_{1s}(w, b) > \delta_1{1} \}
        {\cal J}_{1;0} = \{ s | -\delta_2{1} \le \phi_{1s}(w, b) \le \delta_1{1} \}

    The function calculate_delta is to calculate those \delta_1 and \delta_2 by the quantiles of \phi.

    Args:
        X_train (ndarray): training set: X
        y_train (ndarray): training set: y
        weights (ndarray): parameter w(weight) in classification score = X @ weight + bias,
        bias (float): parameter b(bias) in classification score = X @ weight + bias,
        epsilon (float): epsilon
        base_rate (float): integer rate for In-between set {\cal J}_{0;0} and {\cal J}_{1;0}

    Returns:
        tuple[dict[int, int], dict[int, int]]: tuple[delta_1{0: \delta_1{0}, 1: \delta_1{1}}, delta_2{0: \delta_2{0}, 1: \delta_2{1}}]
    """
    value_ge = {0:[], 1:[]}
    value_le = {0:[], 1:[]}
    delta_1 = {0:1, 1:1}
    delta_2 = {0:1, 1:1}
    index_odd = 0
    positive_index = np.where(y_train == 1)[0].tolist()
    negative_index = np.where(y_train == -1)[0].tolist()
    for s in positive_index:
        # \phi_{0s}^+
        if np.dot(weight, X_train[s]) + bias - 1 > 0:
            value_ge[0].append(np.dot(weight, X_train[s]) + bias - 1)
        elif np.dot(weight, X_train[s]) + bias - 1 < 0:
            value_le[0].append(np.dot(weight, X_train[s]) + bias - 1)
        else:
            if index_odd == 0:
                value_ge[0].append(np.dot(weight, X_train[s]) + bias - 1)
            else:
                value_le[0].append(np.dot(weight, X_train[s]) + bias - 1)
            index_odd += 1
        # \phi_{1s}^+
        if np.dot(weight, X_train[s]) + bias > 0:
            value_ge[1].append(np.dot(weight, X_train[s]) + bias)
        elif np.dot(weight, X_train[s]) + bias < 0:
            value_le[1].append(np.dot(weight, X_train[s]) + bias)
        else:
            if index_odd == 0:
                value_ge[1].append(np.dot(weight, X_train[s]) + bias)
            else:
                value_le[1].append(np.dot(weight, X_train[s]) + bias)
            index_odd += 1
    for s in negative_index:
        # \phi_{0s}^+
        if -np.dot(weight, X_train[s]) - bias - 1 > 0:
            value_ge[0].append(-np.dot(weight, X_train[s]) - bias - 1)
        elif -np.dot(weight, X_train[s]) - bias - 1 < 0:
            value_le[0].append(-np.dot(weight, X_train[s]) - bias - 1)
        else:
            if index_odd == 0:
                value_ge[0].append(-np.dot(weight, X_train[s]) - bias - 1)
            else:
                value_le[0].append(-np.dot(weight, X_train[s]) - bias - 1)
            index_odd += 1
        # \phi_{1s}^-
        if -(np.dot(weight, X_train[s]) + bias) - epsilon > 0:
            value_ge[1].append(-(np.dot(weight, X_train[s]) + bias) - epsilon)
        elif -(np.dot(weight, X_train[s]) + bias) - epsilon < 0:
            value_le[1].append(-(np.dot(weight, X_train[s]) + bias) - epsilon)
        else:
            if index_odd == 0:
                value_ge[1].append(-(np.dot(weight, X_train[s]) + bias) - epsilon)
            else:
                value_le[1].append(-(np.dot(weight, X_train[s]) + bias) - epsilon)
            index_odd += 1
    if base_rate < 100:
        delta_1[0], delta_1[1]= max(1e-5, np.percentile(value_ge[0], base_rate)), max(1e-5, np.percentile(value_ge[1], base_rate))
        delta_2[0], delta_2[1] = max(1e-5, -np.percentile(value_le[0], 100 - base_rate)), max(1e-5, -np.percentile(value_le[1], 100 - base_rate))
    else:
        delta_1[0], delta_1[1] = np.max(value_ge[0]), np.max(value_ge[1])
        delta_2[0], delta_2[1] = -np.min(value_le[0]), -np.min(value_le[1])
    return delta_1, delta_2


def calculate_delta_unconstrained(X_train, y_train, weight, bias, base_rate):
    """
    Similar to the function "calculate_delta", this function "calculate_delta_unconstrained" is used for 
    unconstrained problem, only \delta_1{0} and \delta_2{0} need to be calculated, for 
        {\cal J}_{0;<} = \{ s | \phi_{0s}(w, b) < -\delta_2{0} \}
        {\cal J}_{0;>} = \{ s | \phi_{0s}(w, b) > \delta_1{0} \}
        {\cal J}_{0;0} = \{ s | -\delta_2{0} \le \phi_{0s}(w, b) \le \delta_1{0} \}

    Args:
        X_train (ndarray): training set: X
        y_train (ndarray): training set: y
        weights (ndarray): parameter w in classification score w^\top X+b
        bias (float): parameter b in classification score w^\top X+b
        base_rate (float): integer rate for In-between set {\cal J}_{0;0} and {\cal J}_{1;0}

    Returns:
        tuple[dict[int, int], dict[int, int]]: tuple[delta_1{0: \delta_1{0}}, delta_2{0: \delta_2{0}}]
    """
    value_ge = {0:[]}
    value_le = {0:[]}
    delta_1 = {0:1}
    delta_2 = {0:1}
    index_odd = 0
    positive_index = np.where(y_train == 1)[0].tolist()
    negative_index = np.where(y_train == -1)[0].tolist()
    for s in positive_index:
        # \phi_{0s}^+
        if np.dot(weight, X_train[s]) + bias - 1 > 0:
            value_ge[0].append(np.dot(weight, X_train[s]) + bias - 1)
        elif np.dot(weight, X_train[s]) + bias - 1 < 0:
            value_le[0].append(np.dot(weight, X_train[s]) + bias - 1)
        else:
            if index_odd == 0:
                value_ge[0].append(np.dot(weight, X_train[s]) + bias - 1)
            else:
                value_le[0].append(np.dot(weight, X_train[s]) + bias - 1)
            index_odd += 1
        
    for s in negative_index:
        # \phi_{0s}^+
        if -np.dot(weight, X_train[s]) - bias - 1 > 0:
            value_ge[0].append(-np.dot(weight, X_train[s]) - bias - 1)
        elif -np.dot(weight, X_train[s]) - bias - 1 < 0:
            value_le[0].append(-np.dot(weight, X_train[s]) - bias - 1)
        else:
            if index_odd == 0:
                value_ge[0].append(-np.dot(weight, X_train[s]) - bias - 1)
            else:
                value_le[0].append(-np.dot(weight, X_train[s]) - bias - 1)
            index_odd += 1
        
    if base_rate < 100:
        delta_1[0] = max(1e-5, np.percentile(value_ge[0], base_rate))
        delta_2[0] = max(1e-5, -np.percentile(value_le[0], 100 - base_rate))
    else:
        delta_1[0] = np.max(value_ge[0])
        delta_2[0] = -np.min(value_le[0])
    return delta_1, delta_2


def evaluate_binary(X, y, weight, bias):  # X, y, w, b obtained by PIP
    """
    Evaluate the performance of a binary linear classifier.

    This function computes predictions for a binary classification problem
    using a linear decision rule of the form

        score = X @ weight + bias,

    where samples with nonnegative score are classified as `1` and samples
    with negative score are classified as `-1`.

    In addition to standard classification metrics, the function also evaluates
    how many samples satisfy the margin condition

        y * (X @ weight + bias) - 1 >= 0,

    which indicates that the sample is correctly classified and lies outside
    or on the unit margin.

    Args:
        X: A 2D NumPy array of shape `(n_samples, n_features)` containing the
            feature vectors.

        y: A 1D NumPy array of shape `(n_samples,)` containing the true class
            labels, assumed to take values in `{-1, 1}`.

        weight: A 1D NumPy array of shape `(n_features,)` representing the
            coefficient vector of the linear classifier.

        bias: A scalar representing the intercept term of the linear classifier.

    Returns:
        dict: A dictionary containing the following evaluation metrics:
            - `recall`: recall for the positive class,
            - `precision`: precision for the positive class,
            - `accuracy`: overall classification accuracy,
            - `acc_margin`: proportion of samples satisfying the margin
              condition `y * (X @ weight + bias) >= 1`.

    Notes:
        - Predicted labels are in `{-1, 1}`.
        - The function internally converts the true labels from `{-1, 1}` to
          `{0, 1}` when computing confusion-matrix-based statistics.
        - `acc_margin` is stricter than ordinary accuracy, since it requires
          not only correct classification but also satisfaction of the unit
          margin condition.
    """
    # Calculate predictions
    scores = np.dot(X, weight) + bias
    predictions = np.zeros_like(y)  # Initialize predictions array

    scores_out_of_margin = y*(np.dot(X, weight) + bias)-1
    # Assign predictions based on decision boundary
    predictions[scores >= 0] = 1  # Predict 1 if weight^T X + bias >= 0
    predictions[scores < 0] = -1  # Predict -1 if weight^T X + bias < 0

    # Convert y from -1/1 to 0/1 for compatibility with predictions
    y_binary = (y + 1) // 2  # 1 if y is 1, 0 if y is -1

    # Calculate metrics
    TP = np.sum((predictions == 1) & (y_binary == 1))
    FP = np.sum((predictions == 1) & (y_binary == 0))
    TN = np.sum((predictions == -1) & (y_binary == 0))
    FN = np.sum((predictions == -1) & (y_binary == 1))

    nm_margin = np.sum(scores_out_of_margin>=0)

    # Calculate precision, recall, and accuracy
    precision = TP / (TP + FP) if (TP + FP) > 0 else 0.0
    recall = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    accuracy = (TP + TN) / len(y)
    accuracy_out_of_margin = nm_margin / len(y)
    real_result = {'recall': recall, 'precision': precision, 'accuracy': accuracy, 'acc_margin': accuracy_out_of_margin}

    return real_result


def train_lr_model(X_train, y_train, n_iters=100):
    """
    General the initial solution of MIP / PIP

    Args:
        X_train (ndarray): training set: X
        y_train (ndarray): training set: y
        n_iters (int, optional): iterations of LogisticRegression. Defaults to 100.

    Returns:
        dict[str, Any]: initial w and b
    """
    # Create and train linear classifier
    clf = LogisticRegression(max_iter=n_iters, C=1)
    clf.fit(X_train, y_train) 
    # Calculate metrics and store split results
    result = {'w': clf.coef_[0], 'b': clf.intercept_[0]}
    return result


def sample_data(dataset=None, random_seed=None, positive_size=None, negative_size=None):
    if dataset == 'rice':
        df = pd.read_csv('binary/dataset/rice_cammeo_osmancik.csv', encoding='utf-8')
        # Extract indices where Class == 1 (Cammeo) and Class == 0 (Osmancik)
        indices_cammeo = df.index[df['Class'] == 'Cammeo'].tolist()
        indices_osmancik = df.index[df['Class'] == 'Osmancik'].tolist()
        if random_seed is not None:
            np.random.seed(random_seed)
        # Randomly sample indices
        if positive_size is not None and negative_size is not None:
            # Calculate the number of samples to extract
            num_osmancik_samples = int(min(positive_size, len(indices_osmancik)))
            num_cammeo_samples = int(min(negative_size, len(indices_cammeo)))
            sampled_indices_cammeo = np.random.choice(indices_cammeo, size=num_cammeo_samples, replace=False)
            sampled_indices_osmancik = np.random.choice(indices_osmancik, size=num_osmancik_samples, replace=False)
        else:
            sampled_indices_cammeo = indices_cammeo
            sampled_indices_osmancik = indices_osmancik
        # Combine sampled indices
        sampled_indices = np.concatenate([sampled_indices_cammeo, sampled_indices_osmancik])
        # Get the sampled data
        sampled_data = df.loc[sampled_indices].reset_index(drop=True)
        sampled_data['Class'] = sampled_data['Class'].map({'Osmancik': 1, 'Cammeo': 0})
        # Extract features and Classs
        X_sampled = sampled_data.drop('Class', axis=1)
        y_sampled = sampled_data['Class']

    if dataset == 'hmeq':
        df = pd.read_csv('binary/dataset/fill_hmeq.csv',encoding='utf-8')
        # Extract indices where BAD == 1 (bad) and BAD == 0 (nobad)
        indices_bad = df.index[df['BAD'] == 1].tolist()
        indices_nobad = df.index[df['BAD'] == 0].tolist()
        if random_seed is not None:
            np.random.seed(random_seed)
        # Randomly sample indices
        if positive_size is not None and negative_size is not None:
            # Calculate the number of samples to extract
            num_bad_samples = int(min(positive_size, len(indices_bad)))
            num_nobad_samples = int(min(negative_size, len(indices_nobad)))
            sampled_indices_bad = np.random.choice(indices_bad, size=num_bad_samples, replace=False)
            sampled_indices_nobad = np.random.choice(indices_nobad, size=num_nobad_samples, replace=False)
        else:
            sampled_indices_bad = indices_bad
            sampled_indices_nobad = indices_nobad
        # Combine sample indices
        sampled_indices = np.concatenate([sampled_indices_bad, sampled_indices_nobad])
        # Get the sampled data
        sampled_data = df.loc[sampled_indices].reset_index(drop=True)
        sampled_data['BAD'] = sampled_data['BAD'].map({1: 1, 0: 0})
        # Extract features and BADs
        X_sampled = sampled_data.drop('BAD', axis=1)
        y_sampled = sampled_data['BAD']

    if dataset =='ospi':
        df = pd.read_csv('binary/dataset/online_shoppers_intention_process.csv',encoding='utf-8')
        # Extract indices where BAD == 1 (bad) and BAD == 0 (nobad)
        indices_revenue_true = df.index[df['Revenue'] == 1].tolist()
        indices_revenue_false = df.index[df['Revenue'] == 0].tolist()
        if random_seed is not None:
            np.random.seed(random_seed)
        # Randomly sample indices
        if positive_size is not None and negative_size is not None:
            # Calculate the number of samples to extract
            num_true_samples = int(min(positive_size, len(indices_revenue_true)))
            num_false_samples = int(min(negative_size, len(indices_revenue_false)))
            sampled_indices_true = np.random.choice(indices_revenue_true, size=num_true_samples, replace=False)
            sampled_indices_false = np.random.choice(indices_revenue_false, size=num_false_samples, replace=False)
        else:
            sampled_indices_true = indices_revenue_true
            sampled_indices_false = indices_revenue_false
        # Combine sampled indices
        sampled_indices = np.concatenate([sampled_indices_true, sampled_indices_false])
        # Get the sampled data
        sampled_data = df.loc[sampled_indices].reset_index(drop=True)
        sampled_data['Revenue'] = sampled_data['Revenue'].map({1: 1, 0: 0})
        # Extract features and BADs
        X_sampled = sampled_data.drop('Revenue', axis=1)
        y_sampled = sampled_data['Revenue']

    return X_sampled, y_sampled


def split_data(X, y, random_state = 42):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, stratify = y, random_state = random_state)
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)
    data_splits = {'X_train': X_train, 'y_train': y_train, 'X_test': X_test, 'y_test': y_test}
    return data_splits