from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd


def heaviside_closed(lb, x):
    """Calculate the value of Heaviside function \mathbf{1}_{[lb,\infty)}(x)

    Args:
        lb (float): the left endpoint of the interval of the Heaviside function
        x (float): the variable of the Heaviside function

    Returns:
        int: 0 or 1
    """
    if x >= lb:
        return 1
    else:
        return 0


def heaviside_open(lb, x):
    """Calculate the value of Heaviside function \mathbf{1}_{(lb,\infty)}(x)

    Args:
        lb (float): the left endpoint of the interval of the Heaviside function
        x (float): the variable of the Heaviside function

    Returns:
        int: 0 or 1
    """
    if x > lb:
        return 1
    else:
        return 0


def calculate_gamma(X_train, y_train, weights, bias, beta_p, epsilon):
    positive_index = np.where(y_train == 1)[0].tolist()
    negative_index = np.where(y_train == -1)[0].tolist()
    sum_tp = sum(heaviside_closed(0, np.dot(weights, X_train[s]) + bias) for s in positive_index)  
    sum_dm = sum(heaviside_closed(0, np.dot(weights, X_train[s]) + bias) for s in positive_index) + sum(heaviside_open(-epsilon, np.dot(weights, X_train[s]) + bias) for s in negative_index)
    gamma = max(0, - (sum_tp - beta_p * sum_dm))
    
    z_plus_0_start = {}
    z_plus_start = {}
    z_minus_start = {}

    for s in positive_index:
        z_plus_0_start[s] = heaviside_closed(0, np.dot(weights, X_train[s]) + bias - 1)
        z_plus_start[s] = heaviside_closed(0, np.dot(weights, X_train[s]) + bias)
    for s in negative_index:
        z_plus_0_start[s] = heaviside_closed(0, -np.dot(weights, X_train[s]) - bias - 1)
        z_minus_start[s] = heaviside_closed(0, -(np.dot(weights, X_train[s]) + bias) - epsilon)
    return gamma, z_plus_0_start, z_plus_start, z_minus_start  # if gamma > 0, initial solution generated by LinearClassifier is not feasible


def calculate_z(X_train, y_train, weights, bias):
    positive_index = np.where(y_train == 1)[0].tolist()
    negative_index = np.where(y_train == -1)[0].tolist()
    
    z_plus_0_start = {}
    
    for s in positive_index:
        z_plus_0_start[s] = heaviside_closed(0, np.dot(weights, X_train[s]) + bias - 1)
        
    for s in negative_index:
        z_plus_0_start[s] = heaviside_closed(0, -np.dot(weights, X_train[s]) - bias - 1)
        
    return z_plus_0_start


def calculate_delta(X_train, y_train, weight, bias, epsilon, base_rate):
    value_ge = {0:[], 1:[]}
    value_le = {0:[], 1:[]}
    delta_1 = {0:1, 1:1}
    delta_2 = {0:1, 1:1}
    index_odd = 0
    positive_index = np.where(y_train == 1)[0].tolist()
    negative_index = np.where(y_train == -1)[0].tolist()
    for s in positive_index:
        # \phi_{0s}^+
        if np.dot(weight, X_train[s]) + bias - 1 > 0:
            value_ge[0].append(np.dot(weight, X_train[s]) + bias - 1)
        elif np.dot(weight, X_train[s]) + bias - 1 < 0:
            value_le[0].append(np.dot(weight, X_train[s]) + bias - 1)
        else:
            if index_odd == 0:
                value_ge[0].append(np.dot(weight, X_train[s]) + bias - 1)
            else:
                value_le[0].append(np.dot(weight, X_train[s]) + bias - 1)
            index_odd += 1
        # \phi_{1s}^+
        if np.dot(weight, X_train[s]) + bias > 0:
            value_ge[1].append(np.dot(weight, X_train[s]) + bias)
        elif np.dot(weight, X_train[s]) + bias < 0:
            value_le[1].append(np.dot(weight, X_train[s]) + bias)
        else:
            if index_odd == 0:
                value_ge[1].append(np.dot(weight, X_train[s]) + bias)
            else:
                value_le[1].append(np.dot(weight, X_train[s]) + bias)
            index_odd += 1
    for s in negative_index:
        # \phi_{0s}^+
        if -np.dot(weight, X_train[s]) - bias - 1 > 0:
            value_ge[0].append(-np.dot(weight, X_train[s]) - bias - 1)
        elif -np.dot(weight, X_train[s]) - bias - 1 < 0:
            value_le[0].append(-np.dot(weight, X_train[s]) - bias - 1)
        else:
            if index_odd == 0:
                value_ge[0].append(-np.dot(weight, X_train[s]) - bias - 1)
            else:
                value_le[0].append(-np.dot(weight, X_train[s]) - bias - 1)
            index_odd += 1
        # \phi_{1s}^-
        if -(np.dot(weight, X_train[s]) + bias) - epsilon > 0:
            value_ge[1].append(-(np.dot(weight, X_train[s]) + bias) - epsilon)
        elif -(np.dot(weight, X_train[s]) + bias) - epsilon < 0:
            value_le[1].append(-(np.dot(weight, X_train[s]) + bias) - epsilon)
        else:
            if index_odd == 0:
                value_ge[1].append(-(np.dot(weight, X_train[s]) + bias) - epsilon)
            else:
                value_le[1].append(-(np.dot(weight, X_train[s]) + bias) - epsilon)
            index_odd += 1
    if base_rate < 100:
        delta_1[0], delta_1[1]= max(1e-5, np.percentile(value_ge[0], base_rate)), max(1e-5, np.percentile(value_ge[1], base_rate))
        delta_2[0], delta_2[1] = max(1e-5, -np.percentile(value_le[0], 100 - base_rate)), max(1e-5, -np.percentile(value_le[1], 100 - base_rate))
    else:
        delta_1[0], delta_1[1] = np.max(value_ge[0]), np.max(value_ge[1])
        delta_2[0], delta_2[1] = -np.min(value_le[0]), -np.min(value_le[1])
    return delta_1, delta_2


def calculate_delta_unconstrained(X_train, y_train, weight, bias, base_rate):
    value_ge = {0:[]}
    value_le = {0:[]}
    delta_1 = {0:1}
    delta_2 = {0:1}
    index_odd = 0
    positive_index = np.where(y_train == 1)[0].tolist()
    negative_index = np.where(y_train == -1)[0].tolist()
    for s in positive_index:
        # \phi_{0s}^+
        if np.dot(weight, X_train[s]) + bias - 1 > 0:
            value_ge[0].append(np.dot(weight, X_train[s]) + bias - 1)
        elif np.dot(weight, X_train[s]) + bias - 1 < 0:
            value_le[0].append(np.dot(weight, X_train[s]) + bias - 1)
        else:
            if index_odd == 0:
                value_ge[0].append(np.dot(weight, X_train[s]) + bias - 1)
            else:
                value_le[0].append(np.dot(weight, X_train[s]) + bias - 1)
            index_odd += 1
        
    for s in negative_index:
        # \phi_{0s}^+
        if -np.dot(weight, X_train[s]) - bias - 1 > 0:
            value_ge[0].append(-np.dot(weight, X_train[s]) - bias - 1)
        elif -np.dot(weight, X_train[s]) - bias - 1 < 0:
            value_le[0].append(-np.dot(weight, X_train[s]) - bias - 1)
        else:
            if index_odd == 0:
                value_ge[0].append(-np.dot(weight, X_train[s]) - bias - 1)
            else:
                value_le[0].append(-np.dot(weight, X_train[s]) - bias - 1)
            index_odd += 1
        
    if base_rate < 100:
        delta_1[0] = max(1e-5, np.percentile(value_ge[0], base_rate))
        delta_2[0] = max(1e-5, -np.percentile(value_le[0], 100 - base_rate))
    else:
        delta_1[0] = np.max(value_ge[0])
        delta_2[0] = -np.min(value_le[0])
    return delta_1, delta_2

def evaluate_binary(X, y, weight, bias):  # X, y, w obtained by PIP, b obtained by PIP
    # Calculate predictions
    scores = np.dot(X, weight) + bias
    predictions = np.zeros_like(y)  # Initialize predictions array

    scores_out_of_margin = y*(np.dot(X, weight) + bias)-1
    # Assign predictions based on decision boundary
    predictions[scores >= 0] = 1  # Predict 1 if weight^T X + bias >= 0
    predictions[scores < 0] = -1  # Predict -1 if weight^T X + bias < 0

    # Convert y from -1/1 to 0/1 for compatibility with predictions
    y_binary = (y + 1) // 2  # 1 if y is 1, 0 if y is -1

    # Calculate metrics
    TP = np.sum((predictions == 1) & (y_binary == 1))
    FP = np.sum((predictions == 1) & (y_binary == 0))
    TN = np.sum((predictions == -1) & (y_binary == 0))
    FN = np.sum((predictions == -1) & (y_binary == 1))

    nm_margin = np.sum(scores_out_of_margin>=0)

    # Calculate precision, recall, and accuracy
    precision = TP / (TP + FP) if (TP + FP) > 0 else 0.0
    recall = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    accuracy = (TP + TN) / len(y)
    accuracy_out_of_margin = nm_margin / len(y)


    real_result = {'recall': recall, 'precision': precision, 'accuracy': accuracy, 'acc_margin': accuracy_out_of_margin}

    return real_result


def train_lr_model(X_train, y_train, n_iters=100):
    # Create and train linear classifier
    clf = LogisticRegression(max_iter=n_iters, C=1)
    clf.fit(X_train, y_train)
    # Predictions
    y_pred_train = clf.predict(X_train)
    w = clf.coef_[0]
    b = clf.intercept_[0]
    decision_values = X_train @ w + b
    y_train_01 = 2*y_train-1
    outside_margin = (y_train_01 * decision_values) > 1
    outside_margin_ratio = np.mean(outside_margin)
    # Calculate metrics and store split results
    result = {'w': clf.coef_[0], 'b': clf.intercept_[0]}

    return result


def sample_data(dataset=None, random_seed=None, positive_size=None, negative_size=None):
    if dataset == 'rice':
        df = pd.read_csv('binary/dataset/rice_cammeo_osmancik.csv', encoding='utf-8')
        # Extract indices where Class == 1 (Cammeo) and Class == 0 (Osmancik)
        indices_cammeo = df.index[df['Class'] == 'Cammeo'].tolist()
        indices_osmancik = df.index[df['Class'] == 'Osmancik'].tolist()
        if random_seed is not None:
            np.random.seed(random_seed)
        # Randomly sample indices
        if positive_size is not None and negative_size is not None:
            # Calculate the number of samples to extract
            num_osmancik_samples = int(min(positive_size, len(indices_osmancik)))
            num_cammeo_samples = int(min(negative_size, len(indices_cammeo)))
            sampled_indices_cammeo = np.random.choice(indices_cammeo, size=num_cammeo_samples, replace=False)
            sampled_indices_osmancik = np.random.choice(indices_osmancik, size=num_osmancik_samples, replace=False)
        else:
            sampled_indices_cammeo = indices_cammeo
            sampled_indices_osmancik = indices_osmancik
        # Combine sampled indices
        sampled_indices = np.concatenate([sampled_indices_cammeo, sampled_indices_osmancik])
        # Get the sampled data
        sampled_data = df.loc[sampled_indices].reset_index(drop=True)
        sampled_data['Class'] = sampled_data['Class'].map({'Osmancik': 1, 'Cammeo': 0})
        # Extract features and Classs
        X_sampled = sampled_data.drop('Class', axis=1)
        y_sampled = sampled_data['Class']

    if dataset == 'hmeq':
        df = pd.read_csv('binary/dataset/fill_hmeq.csv',encoding='utf-8')
        # Extract indices where BAD == 1 (bad) and BAD == 0 (nobad)
        indices_bad = df.index[df['BAD'] == 1].tolist()
        indices_nobad = df.index[df['BAD'] == 0].tolist()
        if random_seed is not None:
            np.random.seed(random_seed)
        # Randomly sample indices
        if positive_size is not None and negative_size is not None:
            # Calculate the number of samples to extract
            num_bad_samples = int(min(positive_size, len(indices_bad)))
            num_nobad_samples = int(min(negative_size, len(indices_nobad)))
            sampled_indices_bad = np.random.choice(indices_bad, size=num_bad_samples, replace=False)
            sampled_indices_nobad = np.random.choice(indices_nobad, size=num_nobad_samples, replace=False)
        else:
            sampled_indices_bad = indices_bad
            sampled_indices_nobad = indices_nobad
        # Combine sample indices
        sampled_indices = np.concatenate([sampled_indices_bad, sampled_indices_nobad])
        # Get the sampled data
        sampled_data = df.loc[sampled_indices].reset_index(drop=True)
        sampled_data['BAD'] = sampled_data['BAD'].map({1: 1, 0: 0})
        # Extract features and BADs
        X_sampled = sampled_data.drop('BAD', axis=1)
        y_sampled = sampled_data['BAD']

    if dataset =='ospi':
        df = pd.read_csv('binary/dataset/online_shoppers_intention_process.csv',encoding='utf-8')
        # Extract indices where BAD == 1 (bad) and BAD == 0 (nobad)
        indices_revenue_true = df.index[df['Revenue'] == 1].tolist()
        indices_revenue_false = df.index[df['Revenue'] == 0].tolist()
        if random_seed is not None:
            np.random.seed(random_seed)
        # Randomly sample indices
        if positive_size is not None and negative_size is not None:
            # Calculate the number of samples to extract
            num_true_samples = int(min(positive_size, len(indices_revenue_true)))
            num_false_samples = int(min(negative_size, len(indices_revenue_false)))
            sampled_indices_true = np.random.choice(indices_revenue_true, size=num_true_samples, replace=False)
            sampled_indices_false = np.random.choice(indices_revenue_false, size=num_false_samples, replace=False)
        else:
            sampled_indices_true = indices_revenue_true
            sampled_indices_false = indices_revenue_false
        # Combine sampled indices
        sampled_indices = np.concatenate([sampled_indices_true, sampled_indices_false])
        # Get the sampled data
        sampled_data = df.loc[sampled_indices].reset_index(drop=True)
        sampled_data['Revenue'] = sampled_data['Revenue'].map({1: 1, 0: 0})
        # Extract features and BADs
        X_sampled = sampled_data.drop('Revenue', axis=1)
        y_sampled = sampled_data['Revenue']

    return X_sampled, y_sampled


def split_data(X, y, random_state = 42):
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.25, stratify=y, random_state=random_state
    )

    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)
    
    data_splits = {'X_train': X_train, 'y_train': y_train, 'X_test': X_test, 'y_test': y_test}

    return data_splits