import numpy as np
import pandas as pd

def generate_epsilon(max_iter):
    """
    Generate a sequence of epsilon values for iterative shrinkage (decays exponentially).
    Epsilon controls the relaxation of constraints during optimization.

    Args:
        max_iter (int): Total number of iterations for shrinkage.

    Returns:
        list: Sequence of epsilon values (length = max_iter).
    """
    epsilon_0 = 0.1
    shrinkage_rate = 0.1
    epsilon = [epsilon_0 * (shrinkage_rate ** (i - 1)) for i in range(1, max_iter + 1)]
    return epsilon

def heaviside_closed(lb, x):
    """
    Calculate the value of Heaviside function \mathbf{1}_{[lb,\infty)}(x)

    Args:
        lb (float): the left endpoint of the interval of the Heaviside function
        x (float): the variable of the Heaviside function

    Returns:
        int: 0 or 1
    """
    if x >= lb:
        return 1
    else:
        return 0


def heaviside_open(lb, x):
    """
    Calculate the value of Heaviside function \mathbf{1}_{(lb,\infty)}(x)

    Args:
        lb (float): the left endpoint of the interval of the Heaviside function
        x (float): the variable of the Heaviside function

    Returns:
        int: 0 or 1
    """
    if x > lb:
        return 1
    else:
        return 0
    
def calculate_gamma(X_train, y_train, weights, bias, beta_p, epsilon):
    """
    Compute the violation amount \gamma and the initial solutions of binary variables z^+_0, z^+, z^- 
    Used in precision constrained problem

    Args:
        X_train (ndarray): training set: X
        y_train (ndarray): training set: y
        weights (ndarray): parameter w in classification score w^\top X+b
        bias (float): parameter b in classification score w^\top X+b
        beta_p (float): precision lower bound
        epsilon (float): epsilon

    Returns:
        tuple[int, dict, dict, dict]: gamma,  z_plus_0_start, z_plus_start, z_minus_start
                                      \gamma, z^+_0,          z^+,          z^-
    """
    positive_index = np.where(y_train == 1)[0].tolist()
    negative_index = np.where(y_train == -1)[0].tolist()
    sum_tp = sum(heaviside_closed(0, np.dot(weights, X_train[s]) + bias) for s in positive_index)  
    sum_dm = sum(heaviside_closed(0, np.dot(weights, X_train[s]) + bias) for s in positive_index) + sum(heaviside_open(-epsilon, np.dot(weights, X_train[s]) + bias) for s in negative_index)
    gamma = max(0, - (sum_tp - beta_p * sum_dm))
    z_plus_0_start, z_plus_start, z_minus_start = {}, {}, {}

    for s in positive_index:
        z_plus_0_start[s] = heaviside_closed(0, np.dot(weights, X_train[s]) + bias - 1)
        z_plus_start[s] = heaviside_closed(0, np.dot(weights, X_train[s]) + bias)
    for s in negative_index:
        z_plus_0_start[s] = heaviside_closed(0, -np.dot(weights, X_train[s]) - bias - 1)
        z_minus_start[s] = heaviside_closed(0, -(np.dot(weights, X_train[s]) + bias) - epsilon)
    return gamma, z_plus_0_start, z_plus_start, z_minus_start  # if gamma > 0, initial solution generated by LinearClassifier is not feasible


def calculate_delta(X_train, y_train, weight, bias, epsilon, ratio):
    """
    The index sets {\cal J}_{0;<}, {\cal J}_{0;>}, {\cal J}_{0;0} and {\cal J}_{1;<}, {\cal J}_{1;>}, {\cal J}_{1;0} are determined by the value
    of \phi(w,b):

        {\cal J}_{0;<} = \{ s | \phi_{0s}(w, b) < -\delta_2{0} \}
        {\cal J}_{0;>} = \{ s | \phi_{0s}(w, b) > \delta_1{0} \}
        {\cal J}_{0;0} = \{ s | -\delta_2{0} \le \phi_{0s}(w, b) \le \delta_1{0} \}

        {\cal J}_{1;<} = \{ s | \phi_{1s}(w, b) < -\delta_2{1} \}
        {\cal J}_{1;>} = \{ s | \phi_{1s}(w, b) > \delta_1{1} \}
        {\cal J}_{1;0} = \{ s | -\delta_2{1} \le \phi_{1s}(w, b) \le \delta_1{1} \}

    The function calculate_delta is to calculate those \delta_1 and \delta_2 by the quantiles of \phi.

    Args:
        X_train (ndarray): training set: X
        y_train (ndarray): training set: y
        weights (ndarray): parameter w(weight) in classification score = X @ weight + bias,
        bias (float): parameter b(bias) in classification score = X @ weight + bias,
        epsilon (float): epsilon
        ratio (float): integer rate for In-between set {\cal J}_{0;0} and {\cal J}_{1;0}

    Returns:
        tuple[dict[int, int], dict[int, int]]: tuple[delta_1{0: \delta_1{0}, 1: \delta_1{1}}, delta_2{0: \delta_2{0}, 1: \delta_2{1}}]
    """
    value_ge = {0:[], 1:[]}
    value_le = {0:[], 1:[]}
    delta_1 = {0:1, 1:1}
    delta_2 = {0:1, 1:1}
    index_odd = 0
    positive_index = np.where(y_train == 1)[0].tolist()
    negative_index = np.where(y_train == -1)[0].tolist()
    for s in positive_index:
        # \phi_{0s}^+
        if np.dot(weight, X_train[s]) + bias - 1 > 0:
            value_ge[0].append(np.dot(weight, X_train[s]) + bias - 1)
        elif np.dot(weight, X_train[s]) + bias - 1 < 0:
            value_le[0].append(np.dot(weight, X_train[s]) + bias - 1)
        else:
            if index_odd == 0:
                value_ge[0].append(np.dot(weight, X_train[s]) + bias - 1)
            else:
                value_le[0].append(np.dot(weight, X_train[s]) + bias - 1)
            index_odd += 1
        # \phi_{1s}^+
        if np.dot(weight, X_train[s]) + bias > 0:
            value_ge[1].append(np.dot(weight, X_train[s]) + bias)
        elif np.dot(weight, X_train[s]) + bias < 0:
            value_le[1].append(np.dot(weight, X_train[s]) + bias)
        else:
            if index_odd == 0:
                value_ge[1].append(np.dot(weight, X_train[s]) + bias)
            else:
                value_le[1].append(np.dot(weight, X_train[s]) + bias)
            index_odd += 1
    for s in negative_index:
        # \phi_{0s}^+
        if -np.dot(weight, X_train[s]) - bias - 1 > 0:
            value_ge[0].append(-np.dot(weight, X_train[s]) - bias - 1)
        elif -np.dot(weight, X_train[s]) - bias - 1 < 0:
            value_le[0].append(-np.dot(weight, X_train[s]) - bias - 1)
        else:
            if index_odd == 0:
                value_ge[0].append(-np.dot(weight, X_train[s]) - bias - 1)
            else:
                value_le[0].append(-np.dot(weight, X_train[s]) - bias - 1)
            index_odd += 1
        # \phi_{1s}^-
        if -(np.dot(weight, X_train[s]) + bias) - epsilon > 0:
            value_ge[1].append(-(np.dot(weight, X_train[s]) + bias) - epsilon)
        elif -(np.dot(weight, X_train[s]) + bias) - epsilon < 0:
            value_le[1].append(-(np.dot(weight, X_train[s]) + bias) - epsilon)
        else:
            if index_odd == 0:
                value_ge[1].append(-(np.dot(weight, X_train[s]) + bias) - epsilon)
            else:
                value_le[1].append(-(np.dot(weight, X_train[s]) + bias) - epsilon)
            index_odd += 1
    if ratio < 100:
        delta_1[0], delta_1[1]= max(1e-5, np.percentile(value_ge[0], ratio)), max(1e-5, np.percentile(value_ge[1], ratio))
        delta_2[0], delta_2[1] = max(1e-5, -np.percentile(value_le[0], 100 - ratio)), max(1e-5, -np.percentile(value_le[1], 100 - ratio))
    else:
        delta_1[0], delta_1[1] = np.max(value_ge[0]), np.max(value_ge[1])
        delta_2[0], delta_2[1] = -np.min(value_le[0]), -np.min(value_le[1])
    return delta_1, delta_2