from binary import MIP_binary
from binary import utils
from datetime import datetime
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression, RidgeClassifier, Perceptron
from sklearn.svm import LinearSVC
from sklearn.exceptions import ConvergenceWarning
from sklearn.metrics import precision_score, accuracy_score, recall_score
import csv
import os
import pandas as pd
import copy
import time
import warnings
import pandas as pd
import gurobipy as gp

# =========== Gurobi Settings ==========
model = gp.Model('Binary')
model.setParam('MIPFocus', 1)
model.setParam('IntegralityFocus', 1)
model.setParam('Threads', 4)
feasibility_tol = 1e-09
model.setParam('FeasibilityTol', feasibility_tol)


# =========== Settings to Solve Binary Classification Problem with or without Precision Constraint ==========
def binary(dataset='blsc', data_splits = None, beta_p_threshold=None):
    """
    Settings and output for binary classification problem with or without precision constraint

    Args:
        dataset (str, optional): Abbreviation of dataset name. Defaults to 'blsc'.
        data_splits (dict, optional): Dictionary to store the split data. Defaults to None.
        beta_p_threshold (float, optional): Precision (lower) threshold to be meet. Defaults to None.
    """
    # Name the result document based on the start time of the experiment
    current_datetime = datetime.now()
    result_dir = 'binary/results'

    # For each (dataset, beta_p), a "result_csv" is created
    result_csv = f'{result_dir}/{dataset}_result_' + current_datetime.strftime("%Y-%m-%d_%H-%M-%S")+'.csv'

    # Header of result_csv
    with open(result_csv, mode='a', newline='') as all_result:
        writer = csv.writer(all_result)
        # The following terms are explained in README.md
        writer.writerow(['run', 'type', 'beta_p', 'objective_value', 'bestbd','optimality_gap', 'time', 'w','b', 'gamma_in_obj', 'train_acc_margin',
                         'train_accuracy', 'train_precision', 'train_recall','test_acc_margin','test_accuracy', 'test_precision','test_recall',
                         'violations_assumption_1', 'violations_assumption_2','violations_feasibilitytol', 'z_integrality_vio'])

    # "sub" means subdirectory
    result_subdir = f'{result_dir}/'+ f'{dataset}_'+ current_datetime.strftime("%Y-%m-%d_%H-%M-%S")
    os.makedirs(result_subdir)

    # "details_csv" records the detailed results of each PIP iteration 
    details_csv = f'{result_subdir}/'+ f'{dataset}_result_' + current_datetime.strftime("%Y-%m-%d_%H-%M-%S")+'.csv'
    with open(details_csv, mode='a', newline='') as details:
        writer = csv.writer(details)
        # The following terms are explained in README.md
        writer.writerow(['run', 'type', 'beta_p', 'shrinkage_iter', 'pip_iter', 'integers', 'integer_rate','objective_value', 'bestbd','optimality_gap', 'w','b','vio_asm_equal_0', 
                         'vio_asm_open_interval','vio_feasibilitytol', 'z_integrality_vio'])

    for run in range(1,5):
        # "sub2" means subsubdirectory, for each run(split) there is a subsubdirectory
        result_sub2dir = result_subdir + f'/split_{run}'
        os.makedirs(result_sub2dir)

        # Extract training and test sets
        X_train = data_splits[run]['X_train']
        y_train = data_splits[run]['y_train']
        X_test = data_splits[run]['X_test']
        y_test = data_splits[run]['y_test']
        start = utils.train_lr_model(X_train, y_train)  # Initial solution generated by Logistic Regression 
        y_train = 2*y_train.values - 1  # convert 0/1 to 1/-1
        y_test = 2*y_test.values - 1
        data = {'X_train': X_train, 'y_train': y_train, 'X_test': X_test, 'y_test': y_test}

        # Set integer ratio
        if dataset == 'rice' or dataset == 'hmeq':
            base_rate = 50        # r'_{init} 
            feasible_rate = 20    # r_{init}
            pip_max_rate = 80     # r_{max}
        if dataset == 'ospi':
            base_rate = 20        # r'_{init} 
            feasible_rate = 10    # r_{init}
            pip_max_rate = 60     # r_{max}
        
        # There are totally 6 methods: 
        if beta_p_threshold is not None:
            # Run methods 1-5: PIP with precision constraint
            # 1: 'full_mip'         Full MIP
            # 2: 'full_mip_t300'    Early MIP (T300)
            # 3: 'full_mip_t600',   Early MIP (T600)
            # 4: 'fixed',           \varepsilon-fixed PIP
            # 5: 'shrinkage',       \varepsilon-shrinkage PIP
            for i in range(len(beta_p_threshold[run])):
                result_sub2dir_beta = result_sub2dir + f'/beta_{i+1}'
                for method in range(1,6):
                    start_copy = copy.deepcopy(start)
                    settings = {'method': method, 'epsilon':1e-4, 'epsilon_nu': 1e-1, 'beta_p':beta_p_threshold[run][i], 'rho': 1e4, 'feasibilitytol': feasibility_tol, 'callback_type': 0}
                    stop_rule = {'timelimit': 3600, 'base_rate': base_rate, 'feasible_rate': feasible_rate, 'pip_max_rate': pip_max_rate, 'unchanged_iters':3, 'max_iteration': 10, 'max_outer_iter': 4}
                    file_path = {'dataset': dataset, 'result_csv': result_csv, 'details_csv': details_csv, 'result_dir': result_dir, 'result_sub2dir': result_sub2dir_beta, 'run': run}
                    MIP_binary.mip_binary(model, data, start_copy, settings, stop_rule, file_path)
        else:
            # Run method 6: PIP without precision constraint
            # 6: 'unconstrained'    PIP without precision constraint (for pareto comparison)
            start_copy = copy.deepcopy(start)
            settings = {'method': 6, 'epsilon':1e-4, 'epsilon_nu': 1e-1, 'beta_p': None, 'rho': 1e4, 'feasibilitytol': feasibility_tol, 'callback_type': 0}
            # 'method': 1. 'full_mip', 2. 'fixed', 3. 'shrinkage'
            stop_rule = {'timelimit': 3600, 'base_rate': base_rate, 'feasible_rate': feasible_rate, 'pip_max_rate': pip_max_rate, 'unchanged_iters':3, 'max_iteration': 10, 'max_outer_iter': 4}
            file_path = {'dataset': dataset, 'result_csv': result_csv, 'details_csv': details_csv, 'result_dir': result_dir, 'result_sub2dir': result_sub2dir, 'run': run}
            MIP_binary.mip_binary(model, data, start_copy, settings, stop_rule, file_path)


# =========== Run binary by PIP with or without precision constraint ==========
def binary_pareto_run_pip():
    dataset_list = ['rice', 'hmeq', 'ospi']
    for dataset in dataset_list:
        X, y = utils.sample_data(dataset=dataset)
        data_splits = {}
        beta_p_threshold = None  # If run PIP with precision constraint, comment out this row
        for run in range(1,5):
            data_splits[run] = utils.split_data(X, y, random_state = 42 + run)
            # Set threshold grid, if run without constraint, comment out the following 3 if's
            if dataset == 'rice':
                beta_p_threshold[run] = [0.92, 0.925, 0.93, 0.935, 0.94, 0.945, 0.95, 0.955, 0.96, 0.965, 0.97]
            if dataset == 'hmeq':
                beta_p_threshold[run] = [0.70, 0.72, 0.74, 0.76, 0.78, 0.80, 0.82, 0.84, 0.86, 0.88, 0.90, 0.92, 0.94, 0.96, 0.98]
            if dataset == 'ospi':
                beta_p_threshold[run] = [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.80, 0.81, 0.82, 0.83, 0.84, 0.85]
        binary(dataset=dataset, data_splits= data_splits, beta_p_threshold=beta_p_threshold)


# =========== Run binary by models in sklearn (LR, SVM, Perceptron, Ridge) ==========
def binary_pareto_run_sklearn():
    dataset_list = ['rice', 'hmeq', 'ospi']
    results = []
    # Define the tuning range of the hyperparameters
    param_grid = {'LogisticRegression': {'C': [0.001, 0.01, 0.1, 1, 10, 100], 'penalty': ['l2', 'l1', 'elasticnet']},
        'SVM': {'C': [0.001, 0.01, 0.1, 1, 10, 100], 'penalty': ['l2', 'l1'], 'loss': ['squared_hinge', 'hinge']},
        'Perceptron': {'alpha': [0.0001, 0.01, 0.1, 1, 10], 'penalty': ['l2', 'l1', 'elasticnet']},
        'Ridge': {'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}}

    for dataset in dataset_list:
        X, y = utils.sample_data(dataset=dataset)
        for run in range(1, 5):
            data_splits = utils.split_data(X, y, random_state=42 + run)
            X_train, y_train, X_test, y_test = data_splits['X_train'], data_splits['y_train'], data_splits['X_test'], data_splits['y_test']

            # Four methods and their corresponding tuning functions
            methods = {'LogisticRegression': LogisticRegression(), 'SVM': LinearSVC(), 'Perceptron': Perceptron(), 'Ridge': RidgeClassifier()}

            # Tune the hyperparameters for each method
            for method_name, model in methods.items():
                # Retrieve the hyperparameter grid 
                grid_search = GridSearchCV(estimator=model, param_grid=param_grid[method_name], cv=5, n_jobs=-1, verbose=1)

                # Record warnings during training
                with warnings.catch_warnings(record=True) as caught_warnings:
                    warnings.simplefilter("always")             # Trigger all warnings
                    start_time = time.time()                    # Record the training start time
                    grid_search.fit(X_train, y_train)           # Execute the grid search training
                    end_time = time.time()                      # Record the training end time
                    training_time = end_time - start_time       # Calculate the training time
                    best_model = grid_search.best_estimator_    # Obtain the optimal model
                    if hasattr(best_model, 'converged_'):       # Check convergence during the training process
                        converged = best_model.converged_
                    else:
                        converged = 'N/A'  # For models without a convergence, set it to 'N/A'
                    # Capture any convergence warnings
                    convergence_warning = any(isinstance(warning.message, ConvergenceWarning) for warning in caught_warnings)
                    # Evaluate on the training set and the test set
                    train_predictions, test_predictions = best_model.predict(X_train), best_model.predict(X_test)
                    train_precision, train_accuracy, train_recall = precision_score(y_train, train_predictions), accuracy_score(y_train, train_predictions), recall_score(y_train, train_predictions)
                    test_precision, test_accuracy, test_recall = precision_score(y_test, test_predictions), accuracy_score(y_test, test_predictions), recall_score(y_test, test_predictions)
                    # Record the results
                    result_row = {
                        'dataset': dataset, 'run': run, 'method': method_name, 'train_precision': train_precision, 'train_accuracy': train_accuracy, 'train_recall': train_recall,
                        'test_precision': test_precision, 'test_accuracy': test_accuracy, 'test_recall': test_recall, 'time': training_time, 'convergence_warning': convergence_warning}
                    results.append(result_row)

    df = pd.DataFrame(results)
    df.to_csv('binary/results/results_for_pareto_comparison.csv', index=False)


# binary_pareto_run_pip()
binary_pareto_run_sklearn()