from binary import MIP_binary
from binary import utils
from datetime import datetime
import gurobipy as gp
import csv
import os
import copy

# =========== Gurobi Settings ==========
model = gp.Model('Binary')
model.setParam('MIPFocus', 1)
model.setParam('IntegralityFocus', 1)
model.setParam('Threads', 4)
feasibility_tol = 1e-09
model.setParam('FeasibilityTol', feasibility_tol)


# =========== Settings to Solve Binary Classification Problem with Precision Constraint ==========
def binary_constraint(dataset='rice', data_splits = None, beta_p=None):
    """
    Settings and output for binary classification problem with precision constraint

    Args:
        dataset (str, optional): Abbreviation of dataset name. Defaults to 'rice'.
        data_splits (dict, optional): Dictionary to store the split data. Defaults to None.
        beta_p (float, optional): Precision (lower) threshold to be meet. Defaults to None.
    """
    # Name the result document based on the start time of the experiment
    current_datetime = datetime.now() 
    result_dir = 'binary/results'

    # For each (dataset, beta_p), a "result_csv" is created
    result_csv = f'{result_dir}/{dataset}_result_' + current_datetime.strftime("%Y-%m-%d_%H-%M-%S")+'.csv'

    # Header of result_csv
    with open(result_csv, mode='a', newline='') as all_result:
        writer = csv.writer(all_result)
        # The following terms are explained in README.md
        writer.writerow(['run', 'type', 'beta_p', 'objective_value', 'bestbd', 'optimality_gap', 'time', 'w','b', 'gamma_in_obj', 'train_acc_margin',
                         'train_accuracy', 'train_precision', 'train_recall','test_acc_margin','test_accuracy', 'test_precision','test_recall',
                         'violations_assumption_1', 'violations_assumption_2','violations_feasibilitytol', 'z_integrality_vio'])
    
    # "sub" means subdirectory
    result_subdir = f'{result_dir}/'+ f'{dataset}_'+ current_datetime.strftime("%Y-%m-%d_%H-%M-%S")
    os.makedirs(result_subdir)

    # "details_csv" records the detailed results of each PIP iteration 
    details_csv = f'{result_subdir}/'+ f'{dataset}_result_' + current_datetime.strftime("%Y-%m-%d_%H-%M-%S")+'.csv'
    with open(details_csv, mode='a', newline='') as details:
        writer = csv.writer(details)
        # The following terms are explained in README.md
        writer.writerow(['run', 'type', 'beta_p', 'shrinkage_iter', 'pip_iter', 'integers', 'integer_rate','objective_value', 'bestbd', 'optimality_gap', 'w','b','vio_asm_equal_0', 'vio_asm_open_interval','vio_feasibilitytol', 'z_integrality_vio'])

    for run in range(1,5):
        # "sub2" means subsubdirectory, for each run(split) there is a subsubdirectory
        result_sub2dir = result_subdir + f'/split_{run}'
        os.makedirs(result_sub2dir)

        # Extract training and test sets
        X_train = data_splits[run]['X_train']
        y_train = data_splits[run]['y_train']
        X_test = data_splits[run]['X_test']
        y_test = data_splits[run]['y_test']
        start = utils.train_lr_model(X_train, y_train)  # Initial solution generated by Logistic Regression 
        y_train = 2*y_train.values - 1                  # convert 0/1 to 1/-1
        y_test = 2*y_test.values - 1
        data = {'X_train': X_train, 'y_train': y_train, 'X_test': X_test, 'y_test': y_test}

        # Set integer ratio
        if dataset == 'rice' or dataset == 'hmeq':
            base_rate = 50        # r'_{init} 
            feasible_rate = 20    # r_{init}
            pip_max_rate = 80     # r_{max}
        if dataset == 'ospi':
            base_rate = 20        # r'_{init} 
            feasible_rate = 10    # r_{init}
            pip_max_rate = 60     # r_{max}
        
        # There are totally 6 methods: 
        # 1: 'full_mip'         Full MIP
        # 2: 'full_mip_t300'    Early MIP (T300)
        # 3: 'full_mip_t600',   Early MIP (T600)
        # 4: 'fixed',           \varepsilon-fixed PIP
        # 5: 'shrinkage',       \varepsilon-shrinkage PIP
        # 6: 'unconstrained'    PIP without precision constraint (for pareto comparison)
        for method in range(1,6):
            start_copy = copy.deepcopy(start)
            settings = {'method': method, 'epsilon':1e-4, 'epsilon_nu': 1e-1, 'beta_p':beta_p, 'rho': 1e4, 'feasibilitytol': feasibility_tol, 'callback_type': 0}
            stop_rule = {'timelimit': 3600, 'base_rate': base_rate, 'feasible_rate': feasible_rate, 'pip_max_rate': pip_max_rate, 'unchanged_iters':3, 'max_iteration': 10, 'max_outer_iter': 4}
            file_path = {'dataset': dataset, 'result_csv': result_csv, 'details_csv': details_csv, 'result_dir': result_dir, 'result_sub2dir': result_sub2dir, 'run': run}
            MIP_binary.mip_binary(model, data, start_copy, settings, stop_rule, file_path)


# =========== Run binary_constraint ==========
def binary_run():
    dataset_list = ['rice', 'hmeq', 'ospi']  # Abbreviation of dataset name
    beta_p_dict = {'rice': [0.96, 0.97, 0.98], 'hmeq': [0.80, 0.85, 0.90], 'ospi': [0.77, 0.79, 0.81]}  # Different precision thresholds
    for dataset in dataset_list:
        X, y = utils.sample_data(dataset=dataset)
        data_splits = {}
        for run in range(1,5):
            data_splits[run] = utils.split_data(X, y, random_state = 42 + run)
        for beta_p in beta_p_dict[dataset]:
            binary_constraint(dataset = dataset, data_splits = data_splits, beta_p = beta_p)


binary_run()